folio-org/ui-plugin-query-builder

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml

We need this plugin published to NPM in order for it to be consumed. Pulled in generic build scripts used by all other FOLIO modules.

Add CI steps for NPM publish

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/TestQuery/ColumnsDropdown/ColumnsDropdown.js

https://issues.folio.org/browse/UIPQB-48 …

UIPQB-48 "Show columns" dropdown doesn't fit in the screen.

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js

UIPQB-51: Dropdown typeahead should use contains not starts with
While it's helpful for …

UIPQB-51: Dropdown typeahead should use contains not starts with

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/query.test.js

[UIPQB-55](https://issues.folio.org/browse/UIPQB-55)
While it's helpful for reviewers to …

UIPQB-55: Regular expressions are incorrect for contains and starts_with operators

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
translations/ui-plugin-query-builder/en.json

Added callout and enable button to make possible retrying of qury test in case of error.
https://issues.folio.org/browse/UIPQB-57
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …

UIPQB-57 400 error should be reported in the UI

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/query.test.js
src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
src/constants/operators.js

https://issues.folio.org/browse/UIPQB-64
- Added support of both variants `$and: [{field: $eq: 'value'}]` and just `{field: $eq: 'value'}` if value is single.
- Refactored constants
- Updated tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …

UIPQB-64 Query builder can’t edit single condition queries without AND wrapper

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.test.js
src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/query.test.js
src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
src/QueryBuilder/QueryBuilder/helpers/selectOptions.test.js
src/constants/operators.js
test/jest/data/entityType.js

After this PR is merged, we will be able to support fields with the "arrayType" type.  
- When selecting this type, we have several options “contains” and “not contains”. 
- this gives as opportunity to submit queries using $contains/$not_contains operators which BE is expecting
Ideally all of the PRs involved in breaking changes would be merged in the …

UIPQB-53 Add support for $contains and $not_contains operators

---

CHANGELOG.md
src/QueryBuilder/ResultViewer/helpers.js

[UIPQB-54](https://issues.folio.org/browse/UIPQB-54)
We added formatting for data type Array.

UIPQB-54: Add support for array fields in query results

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.test.js
src/QueryBuilder/ResultViewer/helpers.js
test/jest/__mock__/index.js
test/jest/__mock__/resizeObserver.mock.js

Prevent errors in 'null' fields for arrayType. Ref:  [UIPQB-70](https://issues.folio.org/browse/UIPQB-70)

UIPQB-70 Array fields support verification

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js

Render dropdown menu for arrayType when operators are contains or not_contains. Ref: [UIPQB-71](https://folio-org.atlassian.net/browse/UIPQB-71)

UIPQB-71 AAllow dropdown menus for array types

---

CHANGELOG.md
src/QueryBuilder/ResultViewer/helpers.js

https://folio-org.atlassian.net/browse/UIPQB-84
Here we added case for handling 0 value in `numberType`
https://github.com/folio-org/ui-plugin-query-builder/assets/72550466/e3d6374a-cb5d-41d4-b0bf-f82bcdb3100f

UIPQB-84: Results viewer doesn't show 0 value for number type

---

src/QueryBuilder/ResultViewer/DynamicTable/DynamicTable.js
src/QueryBuilder/ResultViewer/DynamicTable/DynamicTable.test.js

#88 added support for nested tables within the result viewer, however, in some cases, FQM may return undefined in lieu of an empty JSON-ified array "[]".
Encountering this non-existent values causes the entire list page to crash irrecoverably.

[UIPQB-92] Safely handle nonexistent values for nested fields

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/TestQuery/TestQuery.js
src/QueryBuilder/ResultViewer/ResultViewer.js
src/QueryBuilder/ResultViewer/ResultViewer.test.js
src/QueryBuilder/ResultViewer/helpers.js
src/hooks/useAsyncDataSource.js
src/hooks/useViewerCallbacks.js

https://folio-org.atlassian.net/browse/UIPQB-74
Here we added force visible columns logic, to show affected columns.
https://github.com/folio-org/ui-plugin-query-builder/assets/72550466/87fad71f-47b7-456e-b8af-ac8d59b4065f

UIPQB-74: Non-default fields that are part of the query are automatically displayed as columns

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
src/QueryBuilder/QueryBuilder/TestQuery/TestQuery.js

Aded condition for "run button", if limit exceeded then button will be disabled. Refs [UIPQB-95](https://folio-org.atlassian.net/browse/UIPQB-95)

UIPQB-95 Disable run query button when records limit exceeded

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
src/hooks/useRunQuery.js

Extend runQuery handler with user friendly query string. Required for implementation of [UIBULKED-426](https://folio-org.atlassian.net/browse/UIBULKED-426)

UIPQB-96 Extend runQuery handler with "user-friendly" query param

---

src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js

It's required clear banner after query plugin was closed.

UIPQB-95 clear state after query closed

---

src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/query.test.js

[UIPQB-101: It's not possible to edit list when operator is null/empty](https://github.com/folio-org/ui-plugin-query-builder/pull/105/commits/0c119028363fcbcf785b771b05fb3b88a3420a45)

UIPQB-101: It's not possible to edit list when operator is null/empty

---

src/QueryBuilder/ResultViewer/ResultViewer.js
src/QueryBuilder/ResultViewer/ResultViewer.test.js
src/hooks/useViewerCallbacks.js

When editing (or duplicating) a list, we want to keep the originally selected list of fields, rather than resetting to the defaults.

[UIPQB-104] Use original fields when provided instead of re-selecting defaults

---

src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js

The [implementation of showCallout](https://github.com/folio-org/stripes-acq-components/blob/master/lib/hooks/useShowCallout/useShowCallout.js#L13) **deliberately does not follow** the [UX guidelines](https://ux.folio.org/docs/guidelines/components/callout/) ☹️

[UIPQB-90] Failure toast messages don't disappear automatically

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/query.test.js

In scope of this PR was fixex formatting initial values for query-builder plugin, Now if we get a list of elements, it will be rendered in controls.  Ref: [UIPQB-86](https://folio-org.atlassian.net/browse/UIPQB-86)
Before: 
After

UIPQB-86 The IN operator is incorrectly rendered in the query builder when editing existing queries

---

src/QueryBuilder/QueryBuilder/helpers/query.js

After this PR merged, will be covered case of initial values for In operator and comma separated values:

UIPQB-86 Cover "initial values" case case for comma separated values + IN operator

---

src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/query.test.js
src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js

It's possible for the values to be `undefined` when the column's source has not been loaded (such as when duplicating a list); this ensures our handling of these values can accommodate this.

[UIPQB-107] Fix race condition when loading query using source values

---

CHANGELOG.md
src/QueryBuilder/ResultViewer/ResultViewer.js

Real solution for https://github.com/folio-org/ui-lists/pull/129 / https://github.com/folio-org/ui-lists/pull/130.
Before `columnMapping` was calculated (pulled from local storage/api/etc), it would be an empty object, resulting in a MCL with either no columns or column names just being the field names (`id`, `address`, etc), which would not cause an overflow.  Loading that columnMapping in a frame/render cycle later would cause the names to appear, but the MCL's dimensions would not be recalculated.

[UIPQB-108] Only render the ResultViewer table once columns are loaded

---

CHANGELOG.md
src/QueryBuilder/QueryBuilderPlugin.js
src/hooks/useAsyncDataSource.js
src/hooks/useEntityType.js
src/hooks/useParamsDataSource.js

- After this PR merged QueryClientProvider will be taken from stripes-core
- All query-kyes will be prefixed with namespace
Ref: [UIPQB-113](https://folio-org.atlassian.net/browse/UIPQB-113)

UIPQB-113 Remove local QueryClientProvider from plugin-query-builder

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
src/QueryBuilder/QueryBuilder/helpers/valueBuilder.test.js

https://folio-org.atlassian.net/browse/UIPQB-116
We fixed formatting for value with `IN` and `NOT_IN` operators
https://github.com/folio-org/ui-plugin-query-builder/assets/72550466/87b09666-52ff-48b0-9487-9bdff036743d

UIPQB-116: Correct formatting of in and not in operators in query string when “Value“ column contains text box

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
src/QueryBuilder/QueryBuilder/helpers/selectOptions.test.js
src/constants/operators.js

https://folio-org.atlassian.net/browse/UIPQB-112
Here we changed label for `equals` and `not equals` operators

UIPQB-112: Query builder: Accessibility: Not equal operator value is not read by screenreader

---

src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.test.js
src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
src/QueryBuilder/QueryBuilder/helpers/selectOptions.test.js
src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
src/QueryBuilder/QueryBuilder/helpers/valueBuilder.test.js
src/constants/dataTypes.js
test/jest/data/entityType.js

Adds support for `stringUUIDType`, using the same controls as existing UUID structures.

[UIPQB-118] Support stringUUIDType

---

.github/workflows/build-npm.yml
CHANGELOG.md
src/QueryBuilder/ResultViewer/ResultViewer.js

Fix for:  [UIPQB-131](https://folio-org.atlassian.net/browse/UIPQB-131) - Columns and empty area display in the list details page, when we refresh the page 1st time or duplicate the list
Root cause:
The multiColumn component changed the logic of displaying empty result messages and because of that spinner war was broken;
Solution:
Move logic of showing spinner from the empty message into renderTable method
Demo of the bug:
https://github.com/user-attachments/assets/adea3630-e1ca-4ac1-ab5f-e495058219ee
Demo of the fix:
https://github.com/user-attachments/assets/4b140868-3e10-4821-bf05-f26a443e86e5

[UIPQB-131] Update logic of showing spinner

---

CHANGELOG.md
src/QueryBuilder/ResultViewer/ResultViewer.js
src/hooks/useLastNotEmptyValue.js

Fix for [UIPQB-132](https://folio-org.atlassian.net/browse/UIPQB-132)
Root cause: 
We are not saving the preview result and just show that we received in the request during polling but after a limit excides we do not receive content in response as a result we show an empty table even if we had results before.
Solution:
Add a hook that saving not empty results and returns them.

[UIPQB-132] Add useLastNotEmptyValue hook

---

src/QueryBuilder/QueryBuilder/TestQuery/TestQuery.js
src/QueryBuilder/QueryBuilder/TestQuery/ViewerHeadline/ViewerHeadline.js

Cleans up an incorrect prop-type that seems to have been introduced in UIPQB-34: https://github.com/folio-org/ui-plugin-query-builder/commit/b4b935310b0fdafc23a50aa7f081debc0e536494#diff-b125605a4c0eb21cc5cc4b43dbfb3164470971c6024b04292b15e28064018589R89-R101. That commit localized the numbers, turning them into strings, but the prop-type was never updated.
If only we had typescript :(

[UIPQB-134] Fix prop-type for ViewerHeadline

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/helpers/query.js

https://folio-org.atlassian.net/browse/UIPQB-102
Here we removed the incarnation for `slash` since it's  used in query search.
https://github.com/user-attachments/assets/e38c7b8f-5f09-4e68-a449-6037b1298583

UIPQB-102: The 'Organization accounting code' value contains incorrect '\'(backslash) in the query

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/SelectionContainer/SelectionContainer.js

https://folio-org.atlassian.net/browse/UIPQB-147
Here is the fix for filtering values in the `value column` ( case non-sensitive )
https://github.com/user-attachments/assets/8692d8c8-5bc1-47a9-ba71-51be4815ca64

UIPQB-147: Filtering of available values is case sensitive

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js

https://folio-org.atlassian.net/browse/UIPQB-138
Here we added `StripesOverlayWrapper` for `RepeatableField`.
https://github.com/user-attachments/assets/9782a1d6-65f7-4387-88e8-b67c907c79d6
update after `usePortal` prop 
https://github.com/user-attachments/assets/2ea40cec-9e63-4d5c-8193-3ae8666b441f

UIPQB-138: Fix layout for the DatePicker

---

CHANGELOG.md
src/QueryBuilder/ResultViewer/DynamicTable/DynamicTable.js
src/QueryBuilder/ResultViewer/helpers.js
src/QueryBuilder/ResultViewer/utils.js

https://folio-org.atlassian.net/browse/UIPQB-156
Here we add unified formatting for `ResultViewer` and `DynamicalTable`.
Note: `formatValueByDataType` was added to a separate file to prevent the cycle dependency.

UIPQB-156: Nested table data display is inconsistent with regular result viewer

---

CHANGELOG.md
src/QueryBuilder/ResultViewer/ResultViewer.js

https://folio-org.atlassian.net/browse/UIPQB-159
Here we added a condition to `showspinner` if `refreshInProgress` to prevent rendering empty `MLC`.
https://github.com/user-attachments/assets/92cbe3ee-4cfb-43da-9b87-63b05fdfa92c

UIPQB-159: [Lists] Empty columns are displaying when the user duplicates the list and the refresh is in progress

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/query.test.js

https://folio-org.atlassian.net/browse/UIPQB-128
Here, we added a case of parsing a `mongo` query with default values in dropdowns because custom fields used for the query can be deleted. By default, if the field is deleted, we will render the default unselected value inside the query builder to prevent the plugin from crashing.
https://github.com/user-attachments/assets/28c0877a-3466-45ab-a92a-471f1f39bac2

UIPQB-128: Invalid fields handling > Errors when query includes a deleted custom field

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js

https://folio-org.atlassian.net/browse/UIPQB-141
Here we added focus logic to improve accessibility regarding @JohnC-80 comments in the ticket.

UIPQB-141: Modal dialog focus inconsistencies across screenreaders

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/query.test.js
translations/ui-plugin-query-builder/en.json

https://folio-org.atlassian.net/browse/UIPQB-162
Here we added a warning toast for deleted fields.
https://github.com/user-attachments/assets/d7a0750c-0930-45e0-8fe0-b039ffef8847

UIPQB-162: Errors when query includes a modified custom field

---

CHANGELOG.md
src/QueryBuilder/ResultViewer/ResultViewer.js
src/QueryBuilder/ResultViewer/ResultViewer.test.js
src/hooks/useViewerCallbacks.js

https://folio-org.atlassian.net/browse/UIPQB-164
Here we added logic to save selected columns and update new ones after the edit query.
https://github.com/user-attachments/assets/c49521e0-7199-49a4-af9b-821ae7df8c59

UIPQB-164: Columns are reset when user modifies query

---

CHANGELOG.md
src/QueryBuilder/ResultViewer/utils.js

https://folio-org.atlassian.net/browse/UIPQB-185
Here we updated formatter for `JSONb Arrays`.

UIPQB-185: Missing spaces and pipe delimiter for some fields

---

CHANGELOG.md
src/hooks/useViewerCallbacks.js

https://folio-org.atlassian.net/browse/UIPQB-164
Here we fixed ithe ssue with the force visible values. It's follow-up PR.

UIPQB-164: Columns are reset when user modifies query (follow-up)

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
src/QueryBuilder/ResultViewer/utils.js
src/QueryBuilder/ResultViewer/utils.test.js

https://folio-org.atlassian.net/browse/UIPQB-183
https://folio-org.atlassian.net/browse/UIPQB-184
Here we added functionality to show the correct label for custom fields.
https://github.com/user-attachments/assets/2baacb30-8921-45fe-ab6f-f16849a8abcf

UIPQB-183: Show custom field labels in "Query" box of query builder

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/query.test.js

https://folio-org.atlassian.net/browse/UIPQB-187
Here we update the logic for handling deleted custom fields and values from those fields.
https://github.com/user-attachments/assets/e690ea53-c801-488e-aa05-0ca5f6224e3b

UIPQB-187: Ignore/remove invalid values for dropdown fields when editing a query in the query builder

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/TestQuery/TestQuery.js
src/QueryBuilder/QueryBuilder/TestQuery/ViewerHeadline/ViewerHeadline.js
src/QueryBuilder/QueryBuilder/TestQuery/ViewerHeadline/ViewerHeadline.test.js
src/hooks/useViewerCallbacks.js

https://folio-org.atlassian.net/browse/UIPQB-192
We updated cases for the "FAILED" status of a query with 200 status code.

UIPQB-192: Query builder shouldn't show 0 results when a query fails

---

CHANGELOG.md
src/hooks/useViewerCallbacks.js

https://folio-org.atlassian.net/browse/UIPQB-198
Updated logic for setting `defaultColumns` that used inside the `List app.`

UIPQB-198: The columns are missing in the "Actions" dropdown, after modifying the list.

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
src/QueryBuilder/QueryBuilder/helpers/valueBuilder.test.js

https://folio-org.atlassian.net/browse/UIPQB-194
Fix the problem with the placeholder value when changing the unselected value from `COMPARISON` to `ARRAY_COMPARISON` values.

UIPQB-194: The placeholder "Select value" appears as the selected option in the "Values" dropdown.

---

CHANGELOG.md
src/hooks/useViewerCallbacks.js

https://folio-org.atlassian.net/browse/UIPQB-202
Fixed the column reset after editing the query. (The problem comes from `prev` state since after refreshing the list calling the rerender).
https://github.com/user-attachments/assets/4d59fecb-e346-4788-a13d-cbed74aa1b68

UIPQB-202: Columns reset after editing and saving a query

---

CHANGELOG.md
src/QueryBuilder/QueryBuilder/QueryBuilder.js

Consumers need to know if the query builder is opened or not in some use cases, such as controlling form state and page navigation. Without this prop, consuming modules can only know that the QB is open by observing calls to test queries, etc, however, this does not exactly correlate to if the dialog is open, nor does it allow detection of the modal being closed.
`ui-lists` specifically needed this for https://folio-org.atlassian.net/browse/UILISTS-222; before this, Lists had no way of knowing if the QB was open, which was causing erroneous triggers of the "unsaved changes" prompt. Additionally, spying on the existing methods for running queries to change this behavior did not work as navigation happens directly upon the user clicking "Run query & save", disallowing any time for …

[UIPQB-206] Expose new setIsModalShown prop for consumers to determine if the modal is opened

---

src/QueryBuilder/QueryBuilder/QueryBuilderModal/SelectionContainer/SelectionContainer.js

Fix a a small bug introduced in https://github.com/folio-org/ui-plugin-query-builder/pull/243 to allow boolean dropdown menus to start with an initial value of 'Select value'

Fix initial value for boolean dropdowns

---

src/QueryBuilder/QueryBuilder/helpers/query.js
src/QueryBuilder/QueryBuilder/helpers/query.test.js

Use the ✨new✨ (ish) `$contains` and `$starts_with` operators.
This does support parsing queries with `$regex` still; this can be safely removed once [MODFQMMGR-614](https://folio-org.atlassian.net/browse/MODFQMMGR-614) is completed.

[UIPQB-220] Utilize optimized $contains and $regex operators

---

src/QueryBuilder/ResultViewer/ResultViewer.js
src/hooks/useAsyncDataSource.js
src/hooks/useAsyncDataSource.test.js
translations/ui-plugin-query-builder/en.json
translations/ui-plugin-query-builder/en_US.json

Custom ET changes can break attempts to get a list's `/contents`, resulting in a special error code `read-list.contents.request.failed`. When we encounter this error, we want to show a special error message instructing the user to refresh the list.
This is straightforward enough, however, the existing error-handling was a bit awkward and used some anti-patterns in `react-query`. This is now updated to use the builtin retry functionality of `react-query` (unfortunately though, at least in the current obsolete `v3`, there is no way to catch errors before all retries fail, so we do have some extra logic in the `queryFn`). We also added some tests for the negative cases when fetching contents, as all that was previously uncovered.

[UIPQB-243] Provide UI error when custom ET changes break a list
