- src/QueryBuilder/QueryBuilder/QueryBuilder.js
- src/QueryBuilder/ResultViewer/ResultViewer.js
- src/hooks/useAsyncDataSource.js
> UIBULKED-165 add disable options and remove pageSize

- .eslintrc
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.css
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
- src/QueryBuilder/QueryBuilder/QueryBuilderTitle/QueryBuilderTitle.css
- src/QueryBuilder/QueryBuilder/QueryBuilderTitle/QueryBuilderTitle.js
- src/QueryBuilder/QueryBuilder/constants/columnKeys.js
- src/QueryBuilder/QueryBuilder/constants/dataTypes.js
- src/QueryBuilder/QueryBuilder/constants/operators.js
- src/QueryBuilder/QueryBuilder/helpers/query.js
- src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
- test/jest/data/entityType.js
> UIPQB-7 Integer property type - action-value component

- package.json
- src/QueryBuilder/ResultViewer/ResultViewer.js
- src/QueryBuilder/ResultViewer/ResultViewer.test.js
- src/hooks/useAsyncDataSource.js
- src/hooks/useDebounce.js
- test/jest/__mock__/acqComponents.mock.js
https://issues.folio.org/browse/UIPQB-24 …
> UIPQB-24 Add refreshing functionality for query-plugin

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/helpers/query.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
[UIPQB-5](https://issues.folio.org/browse/UIPQB-5)
While it's helpful for reviewers to help …
> UIPQB-5: Field-action-value component: String.

- CHANGELOG.md
- package.json
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
- test/jest/data/entityType.js
https://issues.folio.org/browse/UIPQB-9 …
> UIPQB-9 Date-time property format - action-value component

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
- test/jest/data/entityType.js
> UIPQB-10 Object property type - action-value component

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
- src/QueryBuilder/ResultViewer/ResultViewer.js
- src/QueryBuilder/ResultViewer/ResultViewer.test.js
- src/hooks/useAsyncDataSource.js
- test/jest/data/content.js
https://issues.folio.org/browse/UIPQB-14 …
> UIPQB-14 Build query string

- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
- translations/ui-plugin-query-builder/en.json
> UIPQB-4 Add info text to textarea

- src/QueryBuilder/QueryBuilder/QueryBuilder.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
- src/QueryBuilder/QueryBuilder/helpers/query.js
- src/QueryBuilder/QueryBuilder/helpers/query.test.js
- src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
- src/QueryBuilder/ResultViewer/ResultViewer.js
- src/QueryBuilder/ResultViewer/ResultViewer.test.js
- src/constants/operators.js
- src/hooks/useQuerySource.js
- src/hooks/useRunQuery.js
- test/jest/__mock__/index.js
- test/jest/__mock__/intlProvider.mock.js
- test/jest/__mock__/reactItl.mock.js
- test/jest/setupTests.js
- translations/ui-plugin-query-builder/en.json
https://issues.folio.org/browse/UIPQB-34 …
> UIPQB-34 Localize total number of records

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.test.js
https://issues.folio.org/browse/UIPQB-35 …
> UIPQB-35 Incorrect parsing for multiselect values

- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/SelectionContainer/SelectionContainer.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.test.js
https://issues.folio.org/browse/UIPQB-25 …
> UIPQB-25 Only one option can be selected after "==" and "!=" operators

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
- src/QueryBuilder/QueryBuilder/helpers/query.js
- src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
- src/QueryBuilder/QueryBuilder/helpers/selectOptions.test.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
https://issues.folio.org/browse/UIPQB-40 …
> UIPQB-40 Change rendering behavior with IN operator

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
[UIPQB-36](https://issues.folio.org/browse/UIPQB-36)
While it's helpful for reviewers to …
> UIPQB-36: Add X button for closing the form

- package.json
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
- src/QueryBuilder/QueryBuilder/TestQuery/TestQuery.js
- src/QueryBuilder/QueryBuilder/helpers/query.js
- src/QueryBuilder/QueryBuilder/helpers/query.test.js
- src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
- src/QueryBuilder/propTypes.js
- src/hooks/useQuerySource.js
https://issues.folio.org/browse/UIPQB-40 …
> UIPQB-39 Add new props to query plugin

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder.css
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
- src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
- src/QueryBuilder/QueryBuilder/helpers/selectOptions.test.js
- src/QueryBuilder/QueryBuilder/helpers/timeUtils.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.test.js
https://issues.folio.org/browse/UIPQB-26 …
> UIPQB-26 Validate value entered for integer property type 

- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.test.js
- src/QueryBuilder/QueryBuilder/TestQuery/TestQuery.js
- src/QueryBuilder/propTypes.js
- translations/ui-plugin-query-builder/en.json
https://issues.folio.org/browse/UIPQB-41 …
> UIPQB-41 Show error banner when the limit is exceeded

- src/QueryBuilder/QueryBuilder/QueryBuilder.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/SelectionContainer/SelectionContainer.js
- src/QueryBuilder/QueryBuilder/TestQuery/TestQuery.js
- src/QueryBuilder/QueryBuilder/helpers/query.js
- src/QueryBuilder/QueryBuilder/helpers/query.test.js
- src/QueryBuilder/ResultViewer/ResultViewer.js
- src/hooks/useQuerySource.js
https://issues.folio.org/browse/UIPQB-42 …
> UIPQB-42 Extend edit mode support to plugin

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.test.js
[UIPQB-44](https://issues.folio.org/browse/UIPQB-44)
[UIPQB-43](https://issues.folio.org/browse/UIPQB-43)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> UIPQB-43: upgrade React to v18.

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/helpers/query.js
- src/QueryBuilder/QueryBuilder/helpers/query.test.js
Query builder dies when certain characters are used in combination with regex operators
[UIPQB-45](https://issues.folio.org/browse/UIPQB-45)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UIPQB-45: Query builder dies when certain characters are used in combination with regex operators

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
[UIPQB-46](https://issues.folio.org/browse/UIPQB-46)
While it's helpful for reviewers to …
> UIPQB-46: Incorrect text when no options available in the query builder's search bar

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
- src/hooks/useTestQuery.js
> UIPQB-47: 400 error blocks save or further action in query builder

- src/QueryBuilder/ResultViewer/ResultViewer.js
- src/QueryBuilder/ResultViewer/ResultViewer.test.js
[UIPQB-50](https://issues.folio.org/browse/UIPQB-50)
While it's helpful for reviewers to …
> UIPQB-50: Add 'in-progress' handling to plugin-query-builder

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/helpers/query.js
- src/QueryBuilder/QueryBuilder/helpers/query.test.js
- test/jest/data/entityType.js
After this PR merged, all fields which has type 'string' + in/not in operator, will send as array. Refs [UIPQB-60](https://issues.folio.org/browse/UIPQB-60)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
> UIPQB-60 'In' and 'Not In' requests not properly formatted for [Users] "User ID"

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.test.js
- src/QueryBuilder/QueryBuilder/TestQuery/TestQuery.js
https://issues.folio.org/browse/UIPQB-56
Note: Coverage will be increased it another stories because of unpredictable behavior of jest + react-query interval pulling.
After this PR merged then selected columns inside query builder plugin will be stored untill itis closed.
Ideally all of the PRs involved in breaking changes would be merged in the same day …
> UIPQB-56 Prevent columns from being reset when query is changed

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder.css
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
https://issues.folio.org/browse/UIPQB-67 …
> UIPQB-67 Styles are defined globally for inputs with type "number"

- CHANGELOG.md
- src/QueryBuilder/ResultViewer/ResultViewer.js
- src/QueryBuilder/ResultViewer/helpers.js
- src/hooks/useAsyncDataSource.js
[UIPQB-66](https://issues.folio.org/browse/UIPQB-66)
Here we locolized the date format in MLC. We add util formatter for dateType
https://github.com/folio-org/ui-plugin-query-builder/assets/72550466/3ba6b8cd-6f45-4e66-aedf-dd28513119d2
> UIPQB-66: Localize dates in results view

- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.test.js
- src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
- src/QueryBuilder/QueryBuilder/helpers/selectOptions.test.js
- test/jest/data/entityType.js
Not all fields should be queryable; in these cases, we should not show them as an option in the query builder.
> [UIPQB-91] Ignore non-queryable fields

- src/QueryBuilder/ResultViewer/helpers.js
https://folio-org.atlassian.net/browse/UIPQB-84
Small fix to existing implementation
> UIPQB-84: Results viewer doesn't show 0 value for number type

- src/QueryBuilder/ResultViewer/helpers.js
https://folio-org.atlassian.net/browse/UIPQB-105
As suspected, the bug was in this part of the logic...and not the thousand other places columns are mutated 🙃
> [UIPQB-105] Incorrect alphabetical order in columns list

- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
It's required to clear preview data after modal closed
> UIPQB-113 Change query key

- CHANGELOG.md
- jest.config.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
https://folio-org.atlassian.net/browse/UIPQB-103
We update formating string for query preview with Array type.
> UIPQB-103: Correct formatting of in and not in operators in query string

- CHANGELOG.md
- src/QueryBuilder/ResultViewer/DynamicTable/DynamicTable.css
- src/QueryBuilder/ResultViewer/DynamicTable/DynamicTable.js
Prevent collapsing of inner table columns
> UIPQB-115 Array type fields display strangely on the list details page, after adding them.

- CHANGELOG.md
- src/hooks/useAsyncDataSource.js
https://folio-org.atlassian.net/browse/UIPQB-117
Here we added debounce for contentQueryKeys
> UIPQB-117: Add debounce for contentQueryKeys in useAsyncDataSource

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/TestQuery/ColumnsDropdown/ColumnsDropdown.js
- translations/ui-plugin-query-builder/en.json
After this PR merged it will be possible to filter columns via new search field. Refs [UIPQB-119](https://folio-org.atlassian.net/browse/UIPQB-119)
> UIPQB-119 Filter column names

- CHANGELOG.md
- src/hooks/useAsyncDataSource.js
> UIPQB-140 fix preview to display records when result is more than 100

- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
Addition to [UIPQB-126](https://folio-org.atlassian.net/browse/UIPQB-126)
Wass missing formatting for date value received as a props
Demo of the fix:
https://github.com/user-attachments/assets/89d933ef-775f-4baf-96ee-68c5bc3f5e11
> [UIPQB-126] Add formatting for receiving value for data picker

- src/QueryBuilder/QueryBuilder/helpers/query.js
- src/QueryBuilder/QueryBuilder/helpers/timeUtils.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.test.js
- src/hooks/useQuerySource.js
For India the locale is DD/MM/YYYY
> UIPQB-126:Localizing preview date

- package.json
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.js
- src/QueryBuilder/QueryBuilder/helpers/query.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.test.js
- src/QueryBuilder/ResultViewer/DynamicTable/DynamicTable.js
- src/QueryBuilder/ResultViewer/DynamicTable/DynamicTable.test.js
- src/hooks/useTenantTimezone.js
- src/hooks/useTenantTimezone.test.js
- test/jest/__mock__/intlProvider.mock.js
Must be merged **after**:
- https://github.com/folio-org/ui-bulk-edit/pull/645
- https://github.com/folio-org/ui-lists/pull/218
> [UIPQB-126] Convert local date to UTC with respect to tenant zone

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/TestQuery/TestQuery.js
- src/QueryBuilder/ResultViewer/ResultViewer.test.js
- src/hooks/useAsyncDataSource.js
- src/hooks/useAsyncDataSource.test.js
https://folio-org.atlassian.net/browse/UIPQB-157
Here we added stop polling mechanism for useAsyncDataSource after 3 retries
https://github.com/user-attachments/assets/28d83116-eb49-48ec-b86d-0b0a8d5e2a86
> UIPQB-157: Add stop polling mechanism for useAsyncDataSource after 3 retries

- src/hooks/useAsyncDataSource.js
https://folio-org.atlassian.net/browse/UIPQB-157
Small fix for existing logic
> UIPQB-157: Add stop polling mechanism for useAsyncDataSource after 3 retries (follow-up)

- CHANGELOG.md
- src/QueryBuilder/ResultViewer/ResultViewer.js
- src/hooks/useAsyncDataSource.js
- translations/ui-plugin-query-builder/en.json
https://folio-org.atlassian.net/browse/UIPQB-160
Here we added text in the case when a back-end error stopped polling to improve UX.
> UIPQB-160: Update the text in the query builder after 3 attempts result in 500 errors

- CHANGELOG.md
- package.json
> Release v1.2.5

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/RepeatableFields/RepeatableFields.js
- src/QueryBuilder/QueryBuilder/helpers/selectOptions.js
- src/QueryBuilder/ResultViewer/ResultViewer.js
- src/hooks/useViewerCallbacks.js
https://folio-org.atlassian.net/browse/UIPQB-182
Here we add the possibility to remove the first element from the query.
https://github.com/user-attachments/assets/3bb70168-8c7f-417e-a6ab-9d8289110079
> UIPQB-182: Add ability to remove first query parameter

- src/hooks/useViewerCallbacks.js
https://folio-org.atlassian.net/browse/UIPQB-164
Columns are reset when user modifies query fixed
> UIPQB-164: Columns are reset when user modifies query(follow-up)

- CHANGELOG.md
- src/QueryBuilder/QueryBuilder/helpers/valueBuilder.js
https://folio-org.atlassian.net/browse/UIPQB-181
Here we fixed the problem with boolean values in a user-friendly query with DateType
> UIPQB-181: The user-friendly query contains random dates instead of true/false values

- src/QueryBuilder/QueryBuilder/TestQuery/ViewerHeadline/ViewerHeadline.js
https://folio-org.atlassian.net/browse/UIPQB-192
Here we added missed translation prefix
> UIPQB-192: Query builder shouldn't show 0 results when a query fails(follow-up)

- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
[UIPQB-204](https://folio-org.atlassian.net/browse/UIPQB-204)(follow-up)
Small fix for existing implementation, fixed the name of the field when selecting a value from `plugin-find-organization`
> UIPQB-204: Add plugin-find-organization for "Organization — Name" and "Organization — Code"(follow-up)

- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/SelectionContainer/SelectionContainer.js
[UIPQB-216](https://folio-org.atlassian.net/browse/UIPQB-216): Fix edit-query boolean dropdown options
> [UIPQB-216] Fix edit-query boolean dropdown options

- CHANGELOG.md
- package.json
- src/QueryBuilder/QueryBuilder/QueryBuilder.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/DataTypeInput/DataTypeInput.test.js
- src/QueryBuilder/QueryBuilder/QueryBuilderModal/QueryBuilderModal.test.js
- src/QueryBuilder/ResultViewer/ResultViewer.test.js
- src/hooks/useTenantTimezone.js
- src/hooks/useTenantTimezone.test.js
Use mod-settings API instead of deprecated mod-configuration in `useTenantTimezone`. stripes-core will start use mod-settings after the https://github.com/folio-org/stripes-core/pull/1628
[UIPQB-217](https://folio-org.atlassian.net/browse/UIPQB-217)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> UIPQB-217: useTenantTimezone - use mod-settings API.

- src/QueryBuilder/QueryBuilder/QueryBuilderModal/SelectionContainer/SelectionContainer.js
- translations/ui-plugin-query-builder/en.json
> [UIPQB-237] Re-enable single-select org dropdown
